[project]
name = "python-basilisk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gym>=0.26.2",
    "numpy>=2.2.5",
    "torch>=2.7.0",
]
